# Generated by Django 3.2.16 on 2024-02-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(db_index=True, max_length=30, verbose_name='Слово')),
                ('translate', models.CharField(max_length=30, verbose_name='Перевод')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'слово',
                'verbose_name_plural': 'слова',
                'ordering': ('created_at',),
                'unique_together': {('word', 'translate')},
            },
        ),
    ]
